cbv/basic_app/urls.py
from django.urls import path,include,re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    re_path(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(),name='delete'),
]

cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls',namespace='basic_app')),
]

cbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location =  models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
         return reverse("basic_app:detail",kwargs={'pk':self.pk})


class Student(models.Model):
    name =  models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey('School',on_delete=models.CASCADE,related_name='students')

    def __str__(self):
        return self.name

cbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View,TemplateView,ListView,DetailView,
                                        CreateView,UpdateView,DeleteView)
from . import models

# # Create your views here.
# def index(request):
#     return render(request,'index.html')

# We will create a basic class based view
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("This is a class based View !")

# Now we will create a template view with CBV
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectkey']='This text is injected'
        return context


# Now we will create a List View

class SchoolListView(ListView):
    # if you donot want the default name which is model_list then you can rename it by following
    # context_object_name = 'schools'  --> This will return a variable named as schools
    model=models.School
    #this returns a list named as school_list

class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model=models.School
    # This returns a default variable name as lower case school(model name lower case)
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="#"></a></li>

        </ul>
      </div>

    </nav>


    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend-->
      {% endblock %}

    </div>
  </body>
</html>

cbv/basic_app/templates/basic_app/school_confirm_delete.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <br>
  <a class="btn btn-primary" href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

</form>


{% endblock %}

cbv/basic_app/templates/basic_app/school_detail.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
  <h1>Welcome to details of all the Schools!</h1>
  <h2>School Detail:</h2>
  <p>Name: {{school_details.name}}</p>
  <p>Principal: {{school_details.principal}}</p>
  <p>Loaction: {{school_details.location}}</p>

  <h3>Students:</h3>

  {% for student in school_details.students.all %}
  <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}

</div>

<div class="jumbotron jumbotron-fluid">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>
</div>

{% endblock %}

cbv/basic_app/templates/basic_app/school_form.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

<form class="" method="post">
  {% csrf_token %}
  {{form.as_p}}
   <input class="btn btn-primary" type="submit" value="Submit">

</form>

{% endblock %}

cbv/basic_app/templates/basic_app/school_list.html
<!DOCTYPE html>
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
  <h1>Welcome to a list of all the Schools!</h1>
  <ol>
    {% for school in school_list %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>

</div>

{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="#"></a></li>

        </ul>
      </div>

    </nav>


    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend-->
      {% endblock %}

    </div>
  </body>
</html>

cbv/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}

<div class="jumbotron jumbotron-fluid">
  <h1>HOME PAGE!</h1>
  <h2>Injected Text: {{injectkey}}</h2>
</div>

{% endblock %}